# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tg-sensor\windos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(840, 837)
        Dialog.setSizeGripEnabled(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 811, 791))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setStyleSheet("resource:url(:/penguin.jpg)")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.NewTest = QtWidgets.QWidget()
        self.NewTest.setObjectName("NewTest")
        self.label_12 = QtWidgets.QLabel(self.NewTest)
        self.label_12.setGeometry(QtCore.QRect(10, 430, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.NewTest)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 511, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.NewTest)
        self.label_14.setGeometry(QtCore.QRect(630, 600, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.NewTest)
        self.label_10.setGeometry(QtCore.QRect(90, 30, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.SetDirButton = QtWidgets.QPushButton(self.NewTest)
        self.SetDirButton.setGeometry(QtCore.QRect(550, 260, 75, 31))
        self.SetDirButton.setObjectName("SetDirButton")
        self.label_11 = QtWidgets.QLabel(self.NewTest)
        self.label_11.setGeometry(QtCore.QRect(10, 240, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.NewTest, "")
        self.online = QtWidgets.QWidget()
        self.online.setObjectName("online")
        self.label_2 = QtWidgets.QLabel(self.online)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.online)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber.setGeometry(QtCore.QRect(320, 40, 91, 51))
        self.lcdNumber.setStyleSheet("color:rgb(255, 0, 127)\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_2.setGeometry(QtCore.QRect(450, 40, 91, 51))
        self.lcdNumber_2.setStyleSheet("color:rgb(255, 0, 127)")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_3.setGeometry(QtCore.QRect(580, 40, 91, 51))
        self.lcdNumber_3.setStyleSheet("color:rgb(255, 0, 127)")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_4.setGeometry(QtCore.QRect(320, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_5.setGeometry(QtCore.QRect(450, 120, 91, 51))
        self.lcdNumber_5.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_6.setGeometry(QtCore.QRect(580, 120, 91, 51))
        self.lcdNumber_6.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label_4 = QtWidgets.QLabel(self.online)
        self.label_4.setGeometry(QtCore.QRect(340, 200, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.SampleButton = QtWidgets.QPushButton(self.online)
        self.SampleButton.setGeometry(QtCore.QRect(230, 680, 91, 51))
        self.SampleButton.setObjectName("SampleButton")
        self.StopButton = QtWidgets.QPushButton(self.online)
        self.StopButton.setGeometry(QtCore.QRect(550, 680, 91, 51))
        self.StopButton.setIconSize(QtCore.QSize(48, 48))
        self.StopButton.setObjectName("StopButton")
        self.label = QtWidgets.QLabel(self.online)
        self.label.setGeometry(QtCore.QRect(430, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.online)
        self.label_5.setGeometry(QtCore.QRect(430, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.online)
        self.label_6.setGeometry(QtCore.QRect(560, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.online)
        self.label_7.setGeometry(QtCore.QRect(560, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.online)
        self.label_8.setGeometry(QtCore.QRect(700, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.online)
        self.label_9.setGeometry(QtCore.QRect(700, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.online)
        self.line.setGeometry(QtCore.QRect(50, 90, 701, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.online)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 721, 161))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.online, "")
        self.offline = QtWidgets.QWidget()
        self.offline.setObjectName("offline")
        self.ImportButton = QtWidgets.QPushButton(self.offline)
        self.ImportButton.setGeometry(QtCore.QRect(10, 20, 111, 51))
        self.ImportButton.setObjectName("ImportButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.offline)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 100, 251, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.FFTButton = QtWidgets.QPushButton(self.groupBox_2)
        self.FFTButton.setGeometry(QtCore.QRect(130, 110, 111, 51))
        self.FFTButton.setObjectName("FFTButton")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(50, 30, 71, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 70, 71, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label_15.setObjectName("label_15")
        self.groupBox_3 = QtWidgets.QGroupBox(self.offline)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 330, 251, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 20, 111, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 80, 161, 41))
        self.checkBox_3.setObjectName("checkBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.offline)
        self.groupBox_4.setGeometry(QtCore.QRect(490, 100, 231, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.stabilityButton = QtWidgets.QPushButton(self.groupBox_4)
        self.stabilityButton.setGeometry(QtCore.QRect(90, 100, 131, 61))
        self.stabilityButton.setObjectName("stabilityButton")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_3.setGeometry(QtCore.QRect(160, 20, 61, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(100, 30, 54, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_22.setObjectName("label_22")
        self.start = QtWidgets.QPushButton(self.groupBox_4)
        self.start.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.start.setObjectName("start")
        self.closeee = QtWidgets.QPushButton(self.groupBox_4)
        self.closeee.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.closeee.setObjectName("closeee")
        self.groupBox_5 = QtWidgets.QGroupBox(self.offline)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 330, 251, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.ampEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.ampEdit.setGeometry(QtCore.QRect(70, 20, 91, 31))
        self.ampEdit.setObjectName("ampEdit")
        self.phaseEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.phaseEdit.setGeometry(QtCore.QRect(70, 60, 91, 31))
        self.phaseEdit.setObjectName("phaseEdit")
        self.offsetEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.offsetEdit.setGeometry(QtCore.QRect(70, 100, 91, 31))
        self.offsetEdit.setObjectName("offsetEdit")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 54, 12))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_19.setObjectName("label_19")
        self.CabButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CabButton.setGeometry(QtCore.QRect(170, 10, 75, 81))
        self.CabButton.setObjectName("CabButton")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(170, 110, 31, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 110, 41, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.tabWidget.addTab(self.offline, "")
        self.freq = QtWidgets.QWidget()
        self.freq.setObjectName("freq")
        self.tabWidget.addTab(self.freq, "")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_12.setText(_translate("Dialog", "第二步：进行寄生式时栅自校准"))
        self.label_13.setText(_translate("Dialog", "第三步：进行寄生式时栅光栅对比"))
        self.label_14.setText(_translate("Dialog", "实验愉快"))
        self.label_10.setText(_translate("Dialog", "大型齿轮定位测量中心"))
        self.SetDirButton.setText(_translate("Dialog", "SET"))
        self.label_11.setText(_translate("Dialog", "第一步：设置数据路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NewTest), _translate("Dialog", "Page"))
        self.label_2.setText(_translate("Dialog", "Time-grating sensor"))
        self.label_3.setText(_translate("Dialog", "optical encoder"))
        self.label_4.setText(_translate("Dialog", "Error Profile"))
        self.SampleButton.setText(_translate("Dialog", "采样"))
        self.StopButton.setText(_translate("Dialog", "stop"))
        self.label.setText(_translate("Dialog", "°"))
        self.label_5.setText(_translate("Dialog", "°"))
        self.label_6.setText(_translate("Dialog", "′"))
        self.label_7.setText(_translate("Dialog", "′"))
        self.label_8.setText(_translate("Dialog", "″"))
        self.label_9.setText(_translate("Dialog", "″"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.online), _translate("Dialog", "Online analysis"))
        self.ImportButton.setText(_translate("Dialog", "import data "))
        self.groupBox_2.setTitle(_translate("Dialog", "Fun1"))
        self.FFTButton.setText(_translate("Dialog", "FFT analysis"))
        self.label_16.setText(_translate("Dialog", "end"))
        self.label_15.setText(_translate("Dialog", "start"))
        self.groupBox_3.setTitle(_translate("Dialog", "Fun2"))
        self.checkBox_2.setText(_translate("Dialog", "IIR filter "))
        self.checkBox.setText(_translate("Dialog", "FIR filter"))
        self.checkBox_3.setText(_translate("Dialog", "averaging Windows  "))
        self.groupBox_4.setTitle(_translate("Dialog", "Fun3"))
        self.stabilityButton.setText(_translate("Dialog", "stability analysis "))
        self.label_20.setText(_translate("Dialog", "FFT SIZE"))
        self.label_21.setText(_translate("Dialog", "hanning win"))
        self.label_22.setText(_translate("Dialog", "rect win"))
        self.start.setText(_translate("Dialog", "start"))
        self.closeee.setText(_translate("Dialog", "close"))
        self.groupBox_5.setTitle(_translate("Dialog", "Fun4"))
        self.label_17.setText(_translate("Dialog", "amplitude"))
        self.label_18.setText(_translate("Dialog", "phase"))
        self.label_19.setText(_translate("Dialog", "DC offset"))
        self.CabButton.setText(_translate("Dialog", "Cabliration"))
        self.radioButton.setText(_translate("Dialog", "TG"))
        self.radioButton_2.setText(_translate("Dialog", "OG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.offline), _translate("Dialog", "Offline analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.freq), _translate("Dialog", "System info"))

import configuration_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

