# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tg-sensor\windos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(804, 837)
        Dialog.setSizeGripEnabled(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 721))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setStyleSheet("resource:url(:/penguin.jpg)")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.online = QtWidgets.QWidget()
        self.online.setObjectName("online")
        self.label_2 = QtWidgets.QLabel(self.online)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.online)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber.setGeometry(QtCore.QRect(320, 40, 91, 51))
        self.lcdNumber.setStyleSheet("color:rgb(255, 0, 127)\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_2.setGeometry(QtCore.QRect(450, 40, 91, 51))
        self.lcdNumber_2.setStyleSheet("color:rgb(255, 0, 127)")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_3.setGeometry(QtCore.QRect(580, 40, 91, 51))
        self.lcdNumber_3.setStyleSheet("color:rgb(255, 0, 127)")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_4.setGeometry(QtCore.QRect(320, 120, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_5.setGeometry(QtCore.QRect(450, 120, 91, 51))
        self.lcdNumber_5.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.online)
        self.lcdNumber_6.setGeometry(QtCore.QRect(580, 120, 91, 51))
        self.lcdNumber_6.setStyleSheet("color: rgb(0, 170, 0);")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label_4 = QtWidgets.QLabel(self.online)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 121, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.online)
        self.pushButton.setGeometry(QtCore.QRect(340, 600, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.online)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 600, 91, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.online)
        self.label.setGeometry(QtCore.QRect(430, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.online)
        self.label_5.setGeometry(QtCore.QRect(430, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.online)
        self.label_6.setGeometry(QtCore.QRect(560, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.online)
        self.label_7.setGeometry(QtCore.QRect(560, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.online)
        self.label_8.setGeometry(QtCore.QRect(700, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.online)
        self.label_9.setGeometry(QtCore.QRect(700, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.online)
        self.line.setGeometry(QtCore.QRect(50, 90, 701, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.online)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 721, 181))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.online)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 580, 91, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.online, "")
        self.offline = QtWidgets.QWidget()
        self.offline.setObjectName("offline")
        self.checkBox = QtWidgets.QCheckBox(self.offline)
        self.checkBox.setGeometry(QtCore.QRect(30, 310, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.offline)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 280, 111, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.offline)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 240, 161, 41))
        self.checkBox_3.setObjectName("checkBox_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.offline)
        self.graphicsView_2.setGeometry(QtCore.QRect(60, 360, 701, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.offline)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 30, 131, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.offline)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 30, 111, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.offline)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 90, 151, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.offline, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Time-grating sensor"))
        self.label_3.setText(_translate("Dialog", "optical encoder"))
        self.label_4.setText(_translate("Dialog", "error profile"))
        self.pushButton.setText(_translate("Dialog", "start"))
        self.pushButton_2.setText(_translate("Dialog", "stop"))
        self.label.setText(_translate("Dialog", "°"))
        self.label_5.setText(_translate("Dialog", "°"))
        self.label_6.setText(_translate("Dialog", "′"))
        self.label_7.setText(_translate("Dialog", "′"))
        self.label_8.setText(_translate("Dialog", "″"))
        self.label_9.setText(_translate("Dialog", "″"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.pushButton_3.setText(_translate("Dialog", "Calibration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.online), _translate("Dialog", "Online analysis"))
        self.checkBox.setText(_translate("Dialog", "FIR filter"))
        self.checkBox_2.setText(_translate("Dialog", "IIR filter "))
        self.checkBox_3.setText(_translate("Dialog", "averaging Windows  "))
        self.pushButton_4.setText(_translate("Dialog", "receive data "))
        self.pushButton_5.setText(_translate("Dialog", "import data "))
        self.pushButton_6.setText(_translate("Dialog", "stability analysis "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.offline), _translate("Dialog", "Offline analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "System info"))

import configuration_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

